// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogrNKdANc9G4HZoPtFgOrRBct9TZY-jo',
    appId: '1:638145253536:web:56d2cbe427f9efd29ab9c5',
    messagingSenderId: '638145253536',
    projectId: 'contestify-92b76',
    authDomain: 'contestify-92b76.firebaseapp.com',
    storageBucket: 'contestify-92b76.firebasestorage.app',
    measurementId: 'G-F12MTV4T4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrd4_0E-9lo9RH91dviuXH85BDAMSuZg',
    appId: '1:638145253536:android:b7a7606965fdab459ab9c5',
    messagingSenderId: '638145253536',
    projectId: 'contestify-92b76',
    storageBucket: 'contestify-92b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWcTGD6AsWmsgmoY5SKqowswcq9mNfIE',
    appId: '1:638145253536:ios:09544b624282ff249ab9c5',
    messagingSenderId: '638145253536',
    projectId: 'contestify-92b76',
    storageBucket: 'contestify-92b76.firebasestorage.app',
    iosBundleId: 'com.example.codeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWcTGD6AsWmsgmoY5SKqowswcq9mNfIE',
    appId: '1:638145253536:ios:09544b624282ff249ab9c5',
    messagingSenderId: '638145253536',
    projectId: 'contestify-92b76',
    storageBucket: 'contestify-92b76.firebasestorage.app',
    iosBundleId: 'com.example.codeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCogrNKdANc9G4HZoPtFgOrRBct9TZY-jo',
    appId: '1:638145253536:web:f3f767099ada1e6f9ab9c5',
    messagingSenderId: '638145253536',
    projectId: 'contestify-92b76',
    authDomain: 'contestify-92b76.firebaseapp.com',
    storageBucket: 'contestify-92b76.firebasestorage.app',
    measurementId: 'G-0RLV04CM17',
  );
}
